import { loadEnvConfig } from "@next/env";
import { prisma } from "../lib/prisma";

loadEnvConfig(process.cwd());

const DishCategory = {
  VEG: "VEG",
  NON_VEG: "NON_VEG",
  EGG: "EGG",
} as const;

const MealType = {
  MORNING_DRINK: "MORNING_DRINK",
  MORNING_SNACK: "MORNING_SNACK",
  BREAKFAST: "BREAKFAST",
  BRUNCH: "BRUNCH",
  AFTERNOON_SNACK: "AFTERNOON_SNACK",
  LUNCH: "LUNCH",
  EVENING_SNACK: "EVENING_SNACK",
  DINNER: "DINNER",
  DESSERT: "DESSERT",
  DRINK: "DRINK",
} as const;

const dishes = [
  {
    name: "Masala Chai",
    description: "Indian spiced milk tea.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [
      MealType.MORNING_DRINK,
      MealType.EVENING_SNACK,
      MealType.DRINK,
    ],
  },
  {
    name: "Lemon Honey Water",
    description: "Refreshing morning drink.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_DRINK, MealType.DRINK],
  },
  {
    name: "Jeera Water",
    description: "Cumin infused water.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_DRINK, MealType.DRINK],
  },
  {
    name: "Poha",
    description: "Flattened rice cooked with onions and peanuts.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.BRUNCH],
  },
  {
    name: "Kanda Poha",
    description: "Maharashtrian onion poha.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST],
  },
  {
    name: "Upma",
    description: "Savory semolina breakfast.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST],
  },
  {
    name: "Vegetable Upma",
    description: "Upma loaded with vegetables.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST],
  },
  {
    name: "Idli",
    description: "Steamed rice cakes.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST],
  },
  {
    name: "Medu Vada",
    description: "Crispy lentil doughnuts.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.EVENING_SNACK],
  },
  {
    name: "Plain Dosa",
    description: "Classic crispy dosa.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.DINNER],
  },
  {
    name: "Masala Dosa",
    description: "Potato stuffed dosa.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.DINNER],
  },
  {
    name: "Rava Dosa",
    description: "Crispy semolina dosa.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.DINNER],
  },
  {
    name: "Aloo Paratha",
    description: "Stuffed potato flatbread.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.LUNCH],
  },
  {
    name: "Paneer Paratha",
    description: "Paneer stuffed paratha.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.LUNCH],
  },
  {
    name: "Moong Dal Chilla",
    description: "Protein-rich lentil pancakes.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.DINNER],
  },
  {
    name: "Besan Chilla",
    description: "Gram flour savory pancakes.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.DINNER],
  },
  {
    name: "Vegetable Sandwich",
    description: "Fresh vegetable sandwich.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.BRUNCH],
  },
  {
    name: "Boiled Eggs",
    description: "Simple boiled eggs.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.EGG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.MORNING_SNACK],
  },
  {
    name: "Masala Omelette",
    description: "Indian style omelette.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.EGG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.BRUNCH],
  },
  {
    name: "Fruit Bowl",
    description: "Seasonal mixed fruits.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_SNACK, MealType.AFTERNOON_SNACK],
  },
  {
    name: "Sprouts Salad",
    description: "Healthy sprouted legumes.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_SNACK, MealType.AFTERNOON_SNACK],
  },
  {
    name: "Roasted Makhana",
    description: "Roasted fox nuts.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_SNACK, MealType.EVENING_SNACK],
  },
  {
    name: "Mixed Nuts",
    description: "Almonds, walnuts and cashews.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.MORNING_SNACK, MealType.AFTERNOON_SNACK],
  },
  {
    name: "Khichdi",
    description: "Rice and lentil comfort meal.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Vegetable Pulao",
    description: "Rice cooked with vegetables.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Jeera Rice",
    description: "Cumin flavored rice.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Rajma Chawal",
    description: "Kidney beans with rice.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH],
  },
  {
    name: "Chole Bhature",
    description: "Chickpeas with fried bread.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.BRUNCH],
  },
  {
    name: "Dal Tadka",
    description: "Tempered yellow lentils.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Dal Makhani",
    description: "Creamy black lentils.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Palak Paneer",
    description: "Spinach cooked with paneer.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Shahi Paneer",
    description: "Creamy paneer curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Paneer Butter Masala",
    description: "Rich tomato paneer curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Bhindi Masala",
    description: "Spiced okra curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Aloo Gobi",
    description: "Potato and cauliflower curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Baingan Bharta",
    description: "Roasted eggplant mash.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Mix Veg Curry",
    description: "Seasonal vegetables in gravy.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Kadhi Pakora",
    description: "Yogurt curry with pakoras.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH],
  },
  {
    name: "Sambar Rice",
    description: "Rice served with sambar.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH],
  },
  {
    name: "Curd Rice",
    description: "South Indian comfort meal.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Chicken Curry",
    description: "Classic Indian chicken curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.NON_VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Butter Chicken",
    description: "Creamy tomato chicken curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.NON_VEG,
    suggestedMealTypes: [MealType.DINNER],
  },
  {
    name: "Chicken Biryani",
    description: "Layered aromatic rice and chicken.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.NON_VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Egg Curry",
    description: "Boiled eggs in spicy gravy.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.EGG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Fish Curry",
    description: "Traditional Indian fish curry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.NON_VEG,
    suggestedMealTypes: [MealType.LUNCH, MealType.DINNER],
  },
  {
    name: "Pav Bhaji",
    description: "Spiced vegetable mash with buns.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DINNER],
  },
  {
    name: "Misal Pav",
    description: "Spicy sprout curry with pav.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.BRUNCH],
  },
  {
    name: "Vegetable Soup",
    description: "Light mixed vegetable soup.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DINNER],
  },
  {
    name: "Tomato Soup",
    description: "Creamy tomato soup.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DINNER],
  },
  {
    name: "Samosa",
    description: "Crispy potato stuffed pastry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.EVENING_SNACK],
  },
  {
    name: "Kachori",
    description: "Deep fried stuffed pastry.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.EVENING_SNACK],
  },
  {
    name: "Bhel Puri",
    description: "Puffed rice chaat.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.EVENING_SNACK],
  },
  {
    name: "Dhokla",
    description: "Steamed Gujarati snack.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.EVENING_SNACK],
  },
  {
    name: "Thepla",
    description: "Gujarati spiced flatbread.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.BREAKFAST, MealType.LUNCH],
  },
  {
    name: "Lassi",
    description: "Sweet yogurt drink.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DRINK],
  },
  {
    name: "Mango Lassi",
    description: "Yogurt blended with mango.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DRINK],
  },
  {
    name: "Jalebi",
    description: "Crispy syrup soaked sweet.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DESSERT],
  },
  {
    name: "Gulab Jamun",
    description: "Milk dumplings in sugar syrup.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DESSERT],
  },
  {
    name: "Rasgulla",
    description: "Soft cottage cheese dumplings.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DESSERT],
  },
  {
    name: "Kheer",
    description: "Traditional rice pudding.",
    imageUrl: null,
    recipeUrl: null,
    category: DishCategory.VEG,
    suggestedMealTypes: [MealType.DESSERT],
  },
];

async function main() {
  for (const dish of dishes) {
    await prisma.dish.create({
      data: dish,
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
